# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(599, 652)
        self.stackedWidget = QtGui.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 571, 621))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 561, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(200, 190, 171, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.comboBox_2 = QtGui.QComboBox(self.page)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 240, 201, 27))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(180, 310, 211, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.spinBox = QtGui.QSpinBox(self.page)
        self.spinBox.setGeometry(QtCore.QRect(180, 340, 191, 27))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.pushButton_2 = QtGui.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 510, 99, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.label_6 = QtGui.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 561, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_3 = QtGui.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 480, 99, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.spinBox_2 = QtGui.QSpinBox(self.page_3)
        self.spinBox_2.setGeometry(QtCore.QRect(210, 220, 161, 27))
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.label_7 = QtGui.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(190, 190, 211, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(160, 290, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.spinBox_3 = QtGui.QSpinBox(self.page_3)
        self.spinBox_3.setGeometry(QtCore.QRect(210, 320, 161, 27))
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.label_5 = QtGui.QLabel(self.page_4)
        self.label_5.setGeometry(QtCore.QRect(200, 100, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.textBrowser = QtGui.QTextBrowser(self.page_4)
        self.textBrowser.setGeometry(QtCore.QRect(120, 210, 311, 221))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.label = QtGui.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(50, 60, 471, 91))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox = QtGui.QComboBox(self.page_2)
        self.comboBox.setGeometry(QtCore.QRect(50, 200, 461, 27))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.pushButton = QtGui.QPushButton(self.page_2)
        self.pushButton.setGeometry(QtCore.QRect(230, 400, 99, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Противопожарная защита", None))
        self.label_2.setText(_translate("Form", "Расстояние от возможного очага возгорания до огнетушителя", None))
        self.label_3.setText(_translate("Form", "Выбрать категорию", None))
        self.comboBox_2.setItemText(0, _translate("Form", "Общественные здания", None))
        self.comboBox_2.setItemText(1, _translate("Form", "Категории А, Б, В", None))
        self.comboBox_2.setItemText(2, _translate("Form", "Категория Г", None))
        self.comboBox_2.setItemText(3, _translate("Form", "Категория Д", None))
        self.label_4.setText(_translate("Form", "Введите площать в м кв", None))
        self.pushButton_2.setText(_translate("Form", "Рассчитать", None))
        self.label_6.setText(_translate("Form", "Количество огнетушащего состава на площадь помещения", None))
        self.pushButton_3.setText(_translate("Form", "Рассчитать", None))
        self.label_7.setText(_translate("Form", "Введите площать в м кв", None))
        self.label_8.setText(_translate("Form", "Введите объем огнетушителей (кг)", None))
        self.label_5.setText(_translate("Form", "Результат", None))
        self.label.setText(_translate("Form", "Выберите способ расчёта", None))
        self.comboBox.setItemText(0, _translate("Form", "Расстояние от возможного очага возгорания до огнетушителя", None))
        self.comboBox.setItemText(1, _translate("Form", "Количество огнетушащего состава на площадь помещения", None))
        self.pushButton.setText(_translate("Form", "далее", None))

